/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LyricsPanel: typeof import('./src/components/LyricsPanel.vue')['default']
    PlayerBar: typeof import('./src/components/PlayerBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    TrackDetailModal: typeof import('./src/components/TrackDetailModal.vue')['default']
    TrackList: typeof import('./src/components/TrackList.vue')['default']
    UPagination: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
  }
}
